version: 2.1

executors:
  cypress-node:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107-ff107-edge
    working_directory: ~/repo

jobs:
  test:
    executor: cypress-node
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress tests
          command: npm run test

workflows:
  version: 2
  cypress_test:
    jobs:
      - test
